spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8087}
              predicates:
                - Path=/api/v1/auth/**
            - id: auth-jwks
              uri: ${AUTH_SERVICE_URL:http://localhost:8087}
              predicates:
                - Path=/oauth2/jwks
            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/orders/**
            - id: inventory-service
              uri: ${INVENTORY_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/products/**
            - id: fraud-service
              uri: ${FRAUD_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/api/v1/blocklist/**
            - id: audit-service
              uri: ${AUDIT_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/api/v1/audit-events/**
            # ---- agregação de OpenAPI: expõe o /v3/api-docs de cada serviço sob /aggregate/... ----
            - id: order-service-docs
              uri: ${ORDER_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/aggregate/order-service/v3/api-docs
              filters:
                - RewritePath=/aggregate/order-service/v3/api-docs, /v3/api-docs
            - id: inventory-service-docs
              uri: ${INVENTORY_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/aggregate/inventory-service/v3/api-docs
              filters:
                - RewritePath=/aggregate/inventory-service/v3/api-docs, /v3/api-docs

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_JWKS_URI:http://localhost:8087/oauth2/jwks}

gateway:
  ratelimit:
    limit-for-period: ${GATEWAY_RATELIMIT_LIMIT:100}
    refresh-period: ${GATEWAY_RATELIMIT_REFRESH:PT1S}
    timeout: ${GATEWAY_RATELIMIT_TIMEOUT:PT0S}

springdoc:
  swagger-ui:
    urls:
      - name: order-service
        url: /aggregate/order-service/v3/api-docs
      - name: inventory-service
        url: /aggregate/inventory-service/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

info:
  app:
    name: gateway-service
    version: 1.0.0
    environment: local

server:
  port: 8088

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] correlationId=%X{correlationId:-} %logger{36} - %msg%n"
