spring:
  application:
    name: OrderService

  datasource:
    url: jdbc:postgresql://localhost:5432/orderservice
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092


management:

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true


info:

  app:
    name: OrderService
    version: 1.0.0
    environment: local