spring:
  application:
    name: OrderService

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orderservice}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  jackson:
    deserialization:
      fail-on-unknown-properties: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.lmf.platform.contracts"
        spring.json.use.type.headers: false

    template:
      observation-enabled: true
    listener:
      observation-enabled: true
      ack-mode: record

platform:
  outbox:
    poll-interval-ms: 30000
    dlt-topic: order.created.dlt


management:

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true


info:

  app:
    name: OrderService
    version: 1.0.0
    environment: local

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] correlationId=%X{correlationId:-} %logger{36} - %msg%n"