spring:
  application:
    name: PaymentService

  datasource:
    url: jdbc:postgresql://localhost:5432/paymentservice
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.lmf.payment.paymentservice.events.OrderCreatedEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      ack-mode: record

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: 8082

logging:
  pattern:
    console: >
      %d{yyyy-MM-dd HH:mm:ss}
      [%thread]
      %-5level
      traceId=%X{traceId}
      correlationId=%X{correlationId}
      %logger{36}
      - %msg%n