spring:
  application:
    name: PaymentService

  datasource:
    url: jdbc:postgresql://localhost:5432/paymentservice
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.lmf.payment.events.OrderCreatedEvent

    listener:
      ack-mode: record

server:
  port: 8082